CREATE TABLE IF NOT EXISTS students (
  student_id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(20),
  password_hash VARCHAR(255) NOT NULL,
  date_of_birth DATE,
  gender VARCHAR(20),
  country VARCHAR(100),
  college_id INT,
  college_token VARCHAR(100),
  program VARCHAR(100),
  current_year INT,
  current_semester VARCHAR(20),
  enrollment_year INT,
  current_gpa DECIMAL(3,2),
  academic_interests JSON,
  career_quiz_answers JSON,
  technical_skills JSON,
  soft_skills JSON,
  language_skills JSON,
  primary_goal VARCHAR(100),
  secondary_goal VARCHAR(100),
  timeline VARCHAR(50),
  location_preference VARCHAR(100),
  industry_focus JSON,
  intensity_level VARCHAR(20) DEFAULT 'moderate',
  role VARCHAR(20) DEFAULT 'STUDENT',
  status VARCHAR(20) DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (college_id) REFERENCES colleges(id)
);